### ISSUE TITLE
Embed proguard rules?

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/EitherNet#11]
We may need to do some work here for annotations we read at runtime

**Comment by ZacSweers** [comment]
Let's revisit if we get any reports

**Comment by LloydBlv** [comment]
Could the following be something to look into? @ZacSweers 

```
FATAL EXCEPTION: main
                                                                                                    Process: com.example.picsum, PID: 13363
                                                                                                    java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
                                                                                                    	at retrofit2.HttpServiceMethod$CallAdapted.retrofit2.HttpServiceMethod.parseAnnotations(SourceFile:72)
                                                                                                                                                retrofit2.ServiceMethod.parseAnnotations
                                                                                                                                                V3.HttpServiceMethod$CallAdapted.parseAnnotations
                                                                                                    	at retrofit2.Retrofit.loadServiceMethod(SourceFile:25)
                                                                                                    	at retrofit2.Retrofit$1.invoke(SourceFile:40)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy2.a(Unknown Source)
                                                                                                    	at androidx.compose.ui.text.font.PlatformFontFamilyTypefaceAdapter.B(SourceFile:57)
                                                                                                    	at com.example.domain.models.usecases.GetPhotosUseCase$createObservable$1.invokeSuspend(SourceFile:55)
                                                                                                    	at com.example.domain.models.usecases.GetPhotosUseCase$createObservable$1.invoke(SourceFile:13)
                                                                                                                                                                               invoke
                                                                                                    	at androidx.compose.ui.text.font.PlatformFontFamilyTypefaceAdapter.kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:75)
                                                                                                                                                                        kotlinx.coroutines.flow.AbstractFlow.collect
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(SourceFile:62)
                                                                                                                                                            kotlinx.coroutines.flow.FlowKt.emitAll
                                                                                                                                                            com.example.domain.models.SubjectInteractor$special$$inlined$flatMapLatest$1.invokeSuspend
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.com.example.domain.models.SubjectInteractor$special$$inlined$flatMapLatest$1.invoke(SourceFile:25)
                                                                                                                                                            com.example.domain.models.SubjectInteractor$special$$inlined$flatMapLatest$1.invoke
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(SourceFile:35)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(SourceFile:13)
                                                                                                                                                                                      invoke
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(SourceFile:37)
                                                                                                                                             kotlinx.coroutines.CoroutineStart.invoke
                                                                                                                                             start
                                                                                                    	at kotlinx.coroutines.DebugStringsKt.kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(SourceFile:37)
                                                                                                                                          kotlinx.coroutines.BuildersKt.launch
                                                                                                                                          kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default
                                                                                                                                          kotlinx.coroutines.BuildersKt.launch$default
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(SourceFile:109)
                                                                                                    	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(SourceFile:323)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SourceFile:174)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SourceFile:1)
                                                                                                    	at kotlinx.coroutines.flow.DistinctFlowImpl.collect(SourceFile:18)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(SourceFile:47)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(SourceFile:13)
                                                                                                                                                                                  invoke
                                                                                                    	at kotlin.math.MathKt.kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:5)
                                                                                                    	at kotlinx.coroutines.DebugStringsKt.kotlinx.coroutines.CoroutineScopeKt.coroutineScope(SourceFile:10)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(SourceFile:7)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(SourceFile:43)
                                                                                                                                                                    kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo
                                                                                                                                                                    invokeSuspend
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(SourceFile:97)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(SourceFile:7)
                                                                                                                                                         access$performTrampolineDispatch
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: C3.f: [p0.o0@cb78938, I.f@f44ad11, B{Cancelling}@91f0e76, P@de54c77]

```
